version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_app
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "django_project.wsgi:application"]
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
       - ./firebase_credentials.json:/app/firebase_credentials.json  # Montar la clave en el contenedor
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
